### PR TITLE
usystem/dash: remove symlinks

### PR DESCRIPTION
**Pull request by petershh**
Automake 1.17 got released recently, and this has broken symlinks in usystem/dash, preventing it from building successfully. These links are not required actually, so remove them.

### CODE REVIEW

**Comment by petershh** [comment]
Hm, I guess this breaks CI since it has 1.16...

**Comment by heatd** [comment]
```
configure: error: cannot find required auxiliary files: compile missing install-sh
```

**Comment by petershh** [comment]
It's from old PR version. May I ask you to restart CI?

**Comment by heatd** [comment]
> It's from old PR version. May I ask you to restart CI?

It's still failing, looks like it can't autogen missing, install-sh, etc after all?

Maybe the solution is to run ./autogen.sh in setup_build.sh?

**Comment by petershh** [comment]
I now honestly don't know why it works for me. I've even tried to remove autoconf and automake so it couldn't take install-sh from the system, and build still worked. Will try autogen.sh though.

Also, somewhy CI checks out commit fb822ac35de669058b6f069048986972e917dd79, while mine is abd899f9ad2d6dd5461f0c5708b709993e473e82 .

**Comment by heatd** [comment]
Annoying, but LGTM I guess. And we get rid of a bunch of lines checked out on git.

**Comment by heatd** [comment]
Thank you!

**Pull request merged**
